config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'blog_posts#index', as: :root

  resources :blog_posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
  belongs_to :user

  validates :body, presence: true,
            length: {in: 1..100,
                     too_short: "Minimum %{count} characters required",
                     too_long: "Maximum %{count} characters allowed"}
end

app/models/concerns/visible.rb
# frozen_string_literal: true

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end

  def public?
    status == 'public'
  end

  def private?
    status == 'private'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blog_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, presence: true,
            length: {in: 1..16,
                     too_short: "Minimum %{count} character is required",
                     too_long: "Maximum %{count} characters allowed"},
            uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/blog_posts_controller.rb
# Controller for blog posts
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @blog_posts = BlogPost.all.reverse
    end

    def show
        @blog_post = blog_post_by_id
    end

    def new
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = BlogPost.new(blog_post_params.merge(user_id: current_user.id))

        if @blog_post.save
          redirect_to @blog_post
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
        @blog_post = blog_post_by_id
    end

    def update
        @blog_post = blog_post_by_id

        if @blog_post.user == current_user and @blog_post.update(blog_post_params)
          logger.info "Blog Post updated successfully"
          redirect_to @blog_post, notice: 'Blog updated successfully'
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @blog_post = blog_post_by_id
        if @blog_post.user == current_user
            @blog_post.destroy
            logger.info "Blog post deleted successfully"
            redirect_to root_path, status: :see_other, notice: 'Blog Deleted'
        else
            redirect_to root_path, status: :unauthorized, alert: 'You are not authorized'
        end
    end

    private

    def blog_post_by_id
        @blog_post = BlogPost.find(params[:id])
    end

    def blog_post_params
        params.require(:blog_post).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_blog_post, only: [:create, :destroy]
  def create
    @comment = @blog_post.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to blog_post_path(@blog_post)
  end

  def destroy
    @comment = @blog_post.comments.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      redirect_to blog_post_path(@blog_post), status: :see_other, notice: 'Deleted your comment'
    else
      redirect_to blog_post_path(@blog_post), status: :unauthorized, alert: 'You are not authorized'
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/blog_posts/_form.html.erb
<div class="container mt-4">
  <div class="text-center text-3xl"><h1><%= title %></h1></div>
  <div>
    <%= form_with model: blog_post, class: 'max-w-lg mx-auto my-8' do |form| %>
      <div class="mb-4">
        <%= form.label :status, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.select :status, Visible::VALID_STATUSES, { selected: blog_post.status || 'public' }, class: 'form-select block w-full mt-1' %>
      </div>

      <div class="mb-4">
        <%= form.label :title, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.text_field :title, class: 'form-input block w-full mt-1' %>
        <% blog_post.errors.full_messages_for(:title).each do |message| %>
          <small class="text-red-500"><%= message %></small>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :body, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.text_area :body, class: 'form-textarea block w-full mt-1' %><br>
        <% blog_post.errors.full_messages_for(:body).each do |message| %>
          <small class="text-red-500"><%= message %></small>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.submit 'Submit', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline-blue active:bg-blue-800' %>
      </div>
    <% end %>
  </div>

</div>

app/views/blog_posts/edit.html.erb
<%= render 'form', blog_post: @blog_post, title: 'Edit your blog' %>

app/views/blog_posts/index.html.erb
<div class="bg-gray-100 p-8">
  <h1 class="text-4xl font-extrabold text-dark-700 mb-6">Blog Posts</h1>
  <p class="text-gray-600 mb-4">Our blog has <%= pluralize(BlogPost.public_count, 'public post') %></p>

  <ul class="mt-6">
    <% @blog_posts.each do |blog_post| %>
      <% if blog_post.public? or (user_signed_in? and blog_post.user == current_user and blog_post.private? )  %>
        <li class="bg-white rounded-lg shadow-md p-6 mb-4">
          <h2 class="text-2xl font-bold text-dark-700 mb-2"><%= link_to blog_post.title, blog_post, class: 'hover:underline' %></h2>
          <p class="text-gray-700"><%= blog_post.body.slice(0...30) + '....' %></p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/blog_posts/new.html.erb
<%= render 'form', blog_post: @blog_post, title: 'Add a new blog' %>

app/views/blog_posts/show.html.erb
<div class="container mx-auto p-4">
  <div class="bg-white shadow-md rounded-lg p-6 mb-6">
    <div class="flex">
      <h1 class="text-3xl font-bold mb-4"><%= @blog_post.title %></h1>
      <h6 class="text-blue-500 mt-2 ml-4">By <%= @blog_post.user.username %></h6>
    </div>
    <p class="text-gray-700 mb-4"><%= @blog_post.body %></p>
    <% if user_signed_in? and @blog_post.user == current_user %>
      <div class="flex space-x-4">
        <%= link_to 'Edit', edit_blog_post_path(@blog_post), class: 'text-blue-500 hover:underline' %>
        <%= link_to 'Delete', blog_post_path(@blog_post),
                    data: {turbo_method: :delete,
                           turbo_confirm: "Are you sure?" },
                    class: 'text-red-500 hover:underline' %>
      </div>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <%= render 'comments/form' %>
  <% end %>

  <div class="bg-white shadow-md rounded-lg p-1 mb-6">
    <h2 class="font-bold py-2">Comments:</h2>
    <%= render @blog_post.comments.all %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div>
  <strong class="text-gray-800"><%= comment.user.username %>: </strong><%= comment.body %>
</div>
<% if comment.user == current_user %>
  <div class="mt-2">
    <small>
      <%= link_to "Delete", [comment.blog_post, comment],
                  data: { turbo_method: :delete,
                          turbo_confirm: "Are you sure?" },
                  class: 'text-red-500 hover:underline' %>
    </small>
  </div>
<% end %>

app/views/comments/_form.html.erb
<h3 class="text-xl font-bold mb-4">Add a comment:</h3>
<div class="py-2">
  <%= form_with model: [@blog_post, @blog_post.comments.build], class: 'bg-white shadow-md rounded-md p-4' do |form| %>
    <p class="mb-4">
      <%= form.label current_user.username, class: 'block text-gray-700 font-semibold mb-2' %><br>
      <%= form.text_area :body, class: 'w-full p-2 border rounded-md' %>
    </p>
    <p>
      <%= form.submit class: 'bg-blue-500 text-white p-2 rounded-md hover:bg-blue-600' %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/4687413802.js" crossorigin="anonymous"></script>
  </head>

  <body class="bg-gray-100">
  <nav class="bg-blue-500 p-4">
    <div class="container mx-auto flex justify-between items-center">
      <div>
        <%= link_to 'BlogMate', root_path,
                    class: 'self-center text-2xl font-semibold whitespace-nowrap dark:text-white' %>
      </div>
      <div class="flex">
        <% if user_signed_in? %>
          <div class="flex flex-col items-center mr-4">
            <div>
              <i class="fa-solid fa-plus fa-2xl mt-4" style="color: #eeecf3;"></i>
            </div>
            <div>
              <%= link_to 'New', new_blog_post_path, class: 'text-white text-xs' %>
            </div>
          </div>
          <div>
            <%= link_to image_tag("user.png",
                                  alt: :user,
                                  class: 'rounded-full h-10 w-10 mr-4'),
                        edit_user_registration_path %>
          </div>
          <div><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'bg-red-500 text-white py-2 px-4 rounded' %></div>
        <% else  %>
          <div><%= link_to 'Login', new_user_session_path, class: 'text-white mr-4' %></div>
          <div><%= link_to 'Sign up', new_user_registration_path, class: 'text-white' %></div>
        <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="text-center">
      <p class="text-green-600"><%= notice %></p>
      <p class="text-red-600"><%= alert %></p>
    </div>
    <%= yield %>
  </div>

  </body>
</html>